version: '3.9'

services:
  demo-oracle-entityframeworkcore:
    image: ${DOCKER_REGISTRY-}demo-oracle-entityframeworkcore
    build:
      context: .
      dockerfile: DemoOracleEntityFrameworkCore/Dockerfile.develop