create table "course_test"
(
    "course_id" NUMBER(2) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2 INCREMENT BY 2 CONSTRAINT "course_test_nn_course_id" NOT NULL,
    "course_name" VARCHAR2(50) CONSTRAINT "course_test_nn_course_name" NOT NULL,
    CONSTRAINT "course_test_pk_course_id" PRIMARY KEY("course_id")
)
TABLESPACE "TEST_TBS";

create table "student_test"
(
    "student_id" NUMBER(4) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "student_test_nn_student_id" NOT NULL,
    "course_id" NUMBER(2) CONSTRAINT "student_test_nn_course_id" NOT NULL,
    "student_first_name" VARCHAR2(50) CONSTRAINT "student_test_nn_student_first_name" NOT NULL,
    "student_last_name" VARCHAR2(50) CONSTRAINT "student_test_nn_student_last_name" NOT NULL,
    "student_email" VARCHAR2(50) CONSTRAINT "student_test_nn_student_email" NOT NULL,
    "student_birthday" DATE CONSTRAINT "student_test_nn_student_birthday" NOT NULL,
    "student_gender" CHAR(1) DEFAULT '0' CONSTRAINT "student_test_nn_student_gender" NOT NULL,
    CONSTRAINT "student_test_pk_student_id" PRIMARY KEY("student_id"),
    CONSTRAINT "student_test_uq_student_email" UNIQUE("student_email"),
    CONSTRAINT "student_test_0or1_check_gender" CHECK ("student_gender" IN ('0','1')),
    CONSTRAINT "student_test_fk_course_id" FOREIGN KEY("course_id") REFERENCES "course_test"("course_id")
)
TABLESPACE "TEST_TBS";

INSERT INTO "course_test"("course_name") VALUES('GO');
INSERT INTO "course_test"("course_name") VALUES('JAVA');
INSERT INTO "course_test"("course_name") VALUES('JAVASCRIPT');
INSERT INTO "course_test"("course_name") VALUES('PHP');
INSERT INTO "course_test"("course_name") VALUES('PYTHON');

INSERT INTO "student_test"("course_id", "student_first_name", "student_last_name", "student_email", "student_birthday", "student_gender")
VALUES(2, 'Tuấn', 'Lê', 'tuanle@gmail.com', DATE '2000-05-07', '0');
INSERT INTO "student_test"("course_id", "student_first_name", "student_last_name", "student_email", "student_birthday", "student_gender")
VALUES(4, 'Hoàng', 'Trần', 'tranhoang@gmail.com', DATE '2000-06-19', '0');
INSERT INTO "student_test"("course_id", "student_first_name", "student_last_name", "student_email", "student_birthday", "student_gender")
VALUES(6, 'Ngọc', 'Nguyễn', 'ngocnguyen@gmail.com', DATE '2000-03-27', '1');
INSERT INTO "student_test"("course_id", "student_first_name", "student_last_name", "student_email", "student_birthday", "student_gender")
VALUES(8, 'Hà', 'Trần', 'hatran@gmail.com', DATE '2000-10-02', '1');
INSERT INTO "student_test"("course_id", "student_first_name", "student_last_name", "student_email", "student_birthday", "student_gender")
VALUES(10, 'Bảo', 'Ngô', 'baongo@gmail.com', DATE '2000-08-04', '0');
INSERT INTO "student_test"("course_id", "student_first_name", "student_last_name", "student_email", "student_birthday", "student_gender")
VALUES(2, 'Oanh', 'Nguyễn', 'oanhnguyen@gmail.com', DATE '2000-09-02', '1');

COMMIT WORK;